---
# Wait for the replica backup to complete.
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: cluster-migrate
status:
  pgbackrest:
    repos:
    - bound: true
      name: repo1
      stanzaCreated: true
